Controllers/BookController.cs
using Library.Infrastructure;
using Library.Models;
using Library.Models.Repositories;
using Library.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private ISession session;
        private IBookRepository bookRepository;
        private IUserBookRepository userBookRepository;
        private IReturnRequestRepository returnRequestRepository;
        public int PageSize = 5;

        public BookController(IServiceProvider services, IBookRepository bookRepo, IUserBookRepository userBookRepo, IReturnRequestRepository returnRequestRepo)
        {
            session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
            bookRepository = bookRepo;
            userBookRepository = userBookRepo;
            returnRequestRepository = returnRequestRepo;
        }

        public ViewResult List(int? genreId, int bookPage = 1)
        {
            string search;
            if (HttpContext.Request.Query.ContainsKey("search"))
            {
                search = HttpContext.Request.Query["search"].ToString();
                session.SetString("CurrentSearchString", search);
            }
            else
                search = session.GetString("CurrentSearchString");

            IEnumerable<Book> books = bookRepository.Books
                                .Where(b => genreId == null || b.Genre.Id == genreId)
                                .Where(b => string.IsNullOrEmpty(search)
                                            || b.Title.Contains(search)
                                            || b.Author.Contains(search)
                                            || b.Genre.Title.Contains(search))
                                .OrderBy(b => b.Id);
            return View(new BooksListViewModel
            {
                Books = books.Skip((bookPage - 1) * PageSize)
                                .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = bookPage,
                    ItemsPerPage = PageSize,
                    TotalItems = books.Count()
                },
                CurrentGenreId = genreId,
                CurrentSearchString = search
            });
        }

        [Authorize(Roles = Roles.Reader)]
        public ViewResult UserList()
        {
            return View(userBookRepository.UserBooks
                .Where(b => b.UserName == User.Identity.Name 
                    && b.Quantity > b.Returned 
                    && returnRequestRepository.ReturnRequests.Where(r =>r.UserBook.Id == b.Id).Count() == 0)
                .Include(u => u.Book));
        }

        /*  public static bool CheckAnyFieldContains<T>(T obj, string value)
          {
              var props = typeof(T).GetProperties();
              if (props.Count() == 0)
                  return obj.ToString().Contains(value);

              foreach (PropertyInfo prop in props)
              {
                  var mi = typeof(BookController).GetMethod("CheckAnyFieldContains");
                  var m = mi.MakeGenericMethod(prop.PropertyType);
                  if ((bool)m.Invoke(null, new object[] { prop.GetValue(obj), value }))
                      return true;
              }

              return false;
          }*/
    }
}

Controllers/CartController.cs
using Library.Infrastructure;
using Library.Models;
using Library.Models.Repositories;
using Library.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private Cart cart;

        public CartController(IBookRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {

            string modelStateString = TempData["ModelState"]?.ToString() ?? "";
            if (!string.IsNullOrEmpty(modelStateString))
            {
                var listError = JsonConvert.DeserializeObject<Dictionary<string, string>>(modelStateString);
                var modelState = new ModelStateDictionary();
                foreach (var item in listError)
                {
                    modelState.AddModelError(item.Key, item.Value ?? "");
                }

                ViewData.ModelState.Merge(modelState);
            }
            
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.Id == bookId);
            if (book != null)
            {
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.Id == bookId);

            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectResult ClearCart(string returnUrl)
        {
            cart.Clear();
            return Redirect(returnUrl);
        }

    }
}

Views/Shared/BookSummary.cshtml
@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Available</small>
            </span>
        </h4>
    </div>

    <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" name="bookId"
               value="@Model.Id" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            Genre: @Model.Genre.Title, Author: @Model.Author
            @if (User.IsInRole("Reader"))
            {
                <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                    Add To Cart
                </button>
            }
        </span>
    </form>
</div>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary" asp-action="List" asp-controller="Book">Home</a>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">Log Out</a>
            }
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script asp-src-include="/lib/tether/dist/js/*.min.js"></script>
    <script asp-src-include="/lib/bootstrap/js/dist/*.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <title>Library</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-inverse" role="navigation">
        <div class="row">
            <a class="col navbar-brand" href="#">LIBRARY</a>
            <div class="col-3 text-right">
            </div>
            <div class="col-2 text-right">
                @await Component.InvokeAsync("HeaderMenu")
                @if (User.IsInRole("Reader"))
                {
                    @await Component.InvokeAsync("CartSummary")
                }
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="genres" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Views/Shared/_ReactLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="react-container">
        @RenderBody()
    </div>
</body>
</html>